### ISSUE TITLE
ビルド時にminファイルの中身が生成されない

### ISSUE THREAD

**Issue by tkashi** [hifive/hifive-ui-library#138]
hifive-ui-library/build_for_js.xmlを実行すると、
hifive-ui.jsが生成されるが、中身はファイルヘッダーがあるのみになっている。

なお、dev版のhifive-ui.dev.jsは正しく生成されている。

**Comment by fukudayasuo** [comment]
現状パースエラーのあるソースコードがあるため、ビルド時にエラーが出ていてmin版が生成できていません。
各ブランチについてエラー箇所の修正の対応が必要です。

**Comment by fukudayasuo** [comment]
masterブランチでビルドした際にエラーが出ている箇所(末尾カンマの削除や予約語(float, class)の使用箇所)について、
修正を各ブランチで行いました。

masterで各ブランチの修正を取り込んでビルドして、minifyが成功することを確認しました。

**Comment by simdy** [comment]
改めて修正を各ブランチで行い（あるいはマージして）masterにマージ。
